MODULE_NAME := rockstar

_FILES := load_rockstar_bin \
          sort_rockstar_halos

_TESTS := load_rockstar_bin_test \
          sort_rockstar_halos_test

_DEPS := ./../../memory/allocate \
         ./../../memory/copy \
         ./../../io/open_file \
         ./../../io/read_from \
         ./../../avltree/avl_tree \
         ./../halofinder

include ./../../Makefile
