/*
 * examples/matchinghalos/load_mh.c
 * test_file: examples/matchinghalos/load_mh_test.c
 *
 * Loading matching halos output generated by
 * examples/rg_matchfinder/rg_matchfinder
 *
 * Parameters
 * path: path to the matching halos file
 *
 * return: an avl tree contains matching halos
 * the key of the avl nodes is the halo id of the secondary list and the data
 * is a match structure containing the matched halo id (in the primary) list
 * and the goodness of the match
 *
 * author: Saeed Sarpas
 */


#include <stdlib.h>
#include "./load_mh.h"
#include "./../../avltree/avl_insert.h"
#include "./../../io/open_file.h"
#include "./../../memory/allocate.h"


static void go_to_line(FILE*, int);


avltree* load_mh(char *path)
{
  FILE *matches_file = open_file(path, "r");

  go_to_line(matches_file, 9);

  avltree *matches_tree = new_avltree(set_int_key, compare_int_keys);

  int pri_halo_id;
  float dummy;
  match match_holder;

  int i, num_of_matches = get_num_of_mh(path);

  for(i = 0; i < num_of_matches; i++){
    fscanf(matches_file, " %d %e %d %e %f\n", &match_holder.matchid, &dummy,
           &pri_halo_id, &dummy, &match_holder.goodness);

    avl_insert(matches_tree, &pri_halo_id, &match_holder, 1, sizeof(match));
  }

  fclose(matches_file);

  return matches_tree;
}


int get_num_of_mh(char *path)
{
  FILE *matches_file = open_file(path, "r");

  go_to_line(matches_file, 7);

  int num_of_matches;
  fscanf(matches_file, "num of found matches: %d\n", &num_of_matches);

  return num_of_matches;
}


static void go_to_line(FILE *file, int line)
{
  int counter;
  while(counter < line){
    char c = fgetc(file);
    if(c == '\n')
      counter++;
  }
}
