MODULE_NAME := matchinghalos

_FILES := load_mh

_TESTS := load_mh_test

_DEPS := ./../../avltree/avltree \
         ./../../avltree/avl_inorder_traversal \
         ./../../avltree/avl_insert \
         ./../../avltree/avl_delete \
         ./../../memory/allocate \
         ./../../memory/copy \
         ./../../io/open_file

include ./../../Makefile
