/*
 * avltree/avl_inorder_traversal.c
 * test_file: avltree/avl_inorder_traversal_test.c
 *
 * Traversing through the tree in an ascending order
 *
 * parameters
 * tree: A tree generated by new_avltree function
 * func: A function to run on nodes
 * data: Data that will be passed to the function
 *
 * author: Saeed Sarpas
 */


#include "./avl_inorder_traversal.h"


void inorder_traversal(avlnode*, void (*func)(avlnode*, void*), void*);


void avl_inorder_traversal(avltree *tree,
                           void (*func)(avlnode *node, void *data), void *data)
{
  inorder_traversal(tree->root, func, data);
}


void inorder_traversal(avlnode *node, void (*func)(avlnode*, void*), void *data)
{
  if(node == NULL)
    return;

  inorder_traversal(node->left, func, data);
  func(node, data);
  inorder_traversal(node->right, func, data);
}
