MODULE_NAME := avltree

_FILES := avltree \
          avl_insert \
          avl_delete \
          avl_find \
          avl_inorder_traversal

_TESTS := avltree_test \
          avl_insert_test \
          avl_delete_test \
          avl_find_test \
          avl_inorder_traversal_test

_DEPS := ./../memory/allocate \
         ./../memory/copy

include ./../Makefile
