MODULE_NAME := io

_FILES := open_file \
          read_from \
          write_to \
          check_file \
          check_dir

_TESTS := open_file_test \
          read_from_test \
          write_to_test

_DEPS :=

include ./../Makefile
