MODULE_NAME := halofinder

_FILES := halofinder \
          fill_init_volume

_TESTS := halofinder_test \
          fill_init_volume_test

_DEPS := ./../memory/allocate \
         ./../memory/copy \
         ./../vector/vector \
         ./../vector/vector_get \
         ./../vector/vector_push \
         ./../avltree/avltree \
         ./../avltree/avl_find \
         ./../avltree/avl_insert \
         ./../avltree/avl_delete \
         ./../avltree/avl_inorder_traversal \
         ./../grid/row_major_order/point_to_grid \
         ./../grid/row_major_order/three_to_one \
         ./../simulation/snapshot

include ./../Makefile
