MODULE_NAME := halofinder

_FILES := halofinder \
          fill_init_volume

_TESTS := halofinder_test \
          fill_init_volume_test

_DEPS := ./../memory/allocate \
         ./../avltree/avl_tree \
         ./../grid/row_major_order/point_to_grid \
         ./../grid/row_major_order/three_to_one \
         ./../simulation/snapshot

include ./../Makefile
