MODULE_NAME := gadget

_FILES := load_gadget_snap

_TESTS := load_gadget_snap_test

_DEPS := ./../../avltree/avl_tree \
         ./../../memory/allocate \
         ./../../io/read_from

include ./../../Makefile_main
