MODULE_NAME := gadget

_FILES := load_gadget_snap

_TESTS := load_gadget_snap_test

_DEPS := ./../../memory/allocate \
         ./../../io/read_from \
         ./../../simulation/snapshot

include ./../../Makefile_main
