MODULE_NAME := gadget

_FILES := load_gadget_snap \
          sort_gadget_snap

_TESTS := load_gadget_snap_test \
          sort_gadget_snap_test

_DEPS := ./../../memory/allocate \
         ./../../io/read_from

include ./../../Makefile_main
