MODULE_NAME := triplecascade

_FILES := triplecascade

_TESTS := triplecascade_test

_DEPS := ./../mh_cascade/mh_cascade \
         ./../../../avltree/avltree \
         ./../../../avltree/avl_find \
         ./../../../avltree/avl_insert \
         ./../../../avltree/avl_delete \
         ./../../../vector/vector \
         ./../../../vector/vector_push \
         ./../../../ll/ll \
         ./../../../ll/ll_add \
         ./../../../ll/ll_traverse \
         ./../../../memory/allocate \
         ./../../../memory/copy

include ./../../../Makefile
