MODULE_NAME := ll

_FILES := ll \
          ll_add \
          ll_nth

_TESTS := ll_test \
          ll_add_test \
          ll_nth_test

_DEPS := ./../memory/allocate \
         ./../memory/copy

include ./../Makefile
