MODULE_NAME := ll

_FILES := ll \
          ll_add \
          ll_nth \
          ll_traverse

_TESTS := ll_test \
          ll_add_test \
          ll_nth_test \
          ll_traverse_test

_DEPS := ./../memory/allocate \
         ./../memory/copy

include ./../Makefile
