MODULE_NAME := mh_cascade

_FILES := mh_cascade

_TESTS := mh_cascade_test

_DEPS := ./../../../avltree/avltree \
         ./../../../avltree/avl_find \
         ./../../../avltree/avl_insert \
         ./../../../avltree/avl_delete \
         ./../../../ll/ll \
         ./../../../ll/ll_add \
         ./../../../ll/ll_traverse \
         ./../../../memory/allocate \
         ./../../../memory/copy

include ./../../../Makefile
