"""accretionhistory.py
Loading ascii file including information about accretion history, generated by
accretion_history.c module
"""

import numpy as np


class AccretionHistory(object):
    """Accretion History Class"""

    def __init__(self, path):
        """Intializing the class by loading the data"""

        self.dtype = []
        for res in ['256', '512', '1024']:
            self.dtype.extend([
                ('id' + res, np.int),
                ('alpha' + res, np.float),
                ('z30' + res, np.float),
                ('z50' + res, np.float),
                ('z70' + res, np.float)])

        self.history = np.genfromtxt(path, skip_header=1, dtype=self.dtype)
        self.cleanedhistory = None

    def removecorrupteddata(self):
        """Removing corrupted data from self.history"""
        self.cleanedhistory = []

        # Based on the Wechsler model, alphas should be negative
        self.cleanedhistory = [h for h in self.history
                               if h['alpha256'] < 0.0
                               and h['alpha512'] < 0.0
                               and h['alpha1024'] < 0.0]

        self.cleanedhistory = np.array(self.cleanedhistory, dtype=self.dtype)
