MODULE_NAME := simulation

_FILES := snapshot \
          load_snap_from \
          save_snap_to \
          check_if_saved_exist

_TESTS := snapshot_test \
          save_snap_to_test \
          check_if_saved_exist_test

_DEPS := ./../memory/allocate \
         ./../io/open_file \
         ./../io/read_from \
         ./../io/write_to \
         ./../io/check_file \
         ./../strings/concat/concat

include ./../Makefile
