MODULE_NAME := simulation

_FILES := snapshot \
          load_snap_from \
          save_snap_to

_TESTS := snapshot_test \
          save_snap_to_test

_DEPS := ./../memory/allocate \
         ./../io/open_file \
         ./../io/read_from \
         ./../io/write_to

include ./../Makefile
