MODULE_NAME := row_major_order

_FILES := three_to_one \
          one_to_three \
          point_to_grid

_TESTS := three_to_one_test \
          one_to_three_test \
          point_to_grid_test

_DEPS := ./../../memory/allocate

include ./../../Makefile_main
