MODULE_NAME := halomatcher

_FILES := matchinghalo \
          halomatcher

_TESTS := matchinghalo_test \
          halomatcher_test

_DEPS := ./../memory/allocate \
         ./../memory/copy \
         ./../search/half_interval/find_ge \
         ./../avltree/avl_tree \
         ./../vector/vector \
         ./../halofinder/halofinder

include ./../makefile_main
