MODULE_NAME := vector

_FILES := vector \
          vector_push \
          vector_pop \
          vector_get \
          vector_sort

_TESTS := vector_test \
          vector_push_test \
          vector_pop_test \
          vector_get_test \
          vector_sort_test

_DEPS := ./../memory/allocate \
         ./../memory/copy

include ./../Makefile
