MODULE_NAME := fityaebx

_FILES := fityaebx

_TESTS := fityaebx_test

_DEPS := ./../../memory/allocate \
         ./../../memory/copy \
         ./../../vector/vector \
         ./../../vector/vector_get \
         ./../../vector/vector_push

include ./../../Makefile
